export LINODE_TOKEN=''
export LINODE_PASSWORD=''
export LINODE_DATACENTER_ID=4 # Fremnot
export LINODE_PLAN_ID=1 # 1024 MB of RAM
export LINODE_PAYMENT_TERM=1
export LINODE_DISTRIBUTION_ID=146 # Ubuntu 16
export LINODE_KERNEL_ID=210 # GRUB 2
export MANAGER_NAME=my-manager
export NUM_WORKERS=2
export SWARM_WORKERS_PREFIX=my-swarm-node-
export MANAGER_IP=''
export TOKEN=''
export REGISTRY_NAME=''
